In [12]:
#Classification using  Support vector machine
import pandas as pd
import numpy as np
dataset=pd.read_csv('titanic_datasetNew.csv')

print(dataset.shape)

(891, 12)


In [13]:
dataset.head()


PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [14]:
from sklearn.impute import SimpleImputer
dataset.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Survived         0
dtype: int64

In [15]:
dataset = dataset.drop(columns=['Name','Cabin','Embarked',])

In [16]:
dataset.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0            1       3    male  22.0      1      0         A/5 21171   7.2500   
1            2       1  female  38.0      1      0          PC 17599  71.2833   
2            3       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3            4       1  female  35.0      1      0            113803  53.1000   
4            5       3    male  35.0      0      0            373450   8.0500   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [17]:
dataset.isnull().sum()

PassengerId      0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Survived         0
dtype: int64

In [18]:
imp=SimpleImputer(missing_values=np.nan,strategy="mean")
x=dataset.iloc[:,:-1].values


x=dataset.iloc[:,:-1].values


y=dataset.iloc[:,8].values

x
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [19]:
x[:,3:4]=imp.fit_transform(x[:,3:4])


In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,6]=le.fit_transform(x[:,6])
x[:,2]=le.fit_transform(x[:,2])

x

array([[1, 3, 1, ..., 0, 523, 523],
       [2, 1, 0, ..., 0, 596, 596],
       [3, 3, 0, ..., 0, 669, 669],
       ...,
       [889, 3, 0, ..., 2, 675, 675],
       [890, 1, 1, ..., 0, 8, 8],
       [891, 3, 1, ..., 0, 466, 466]], dtype=object)

In [24]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
transform=ColumnTransformer([("norm1",OneHotEncoder(),[2])],remainder='passthrough')

x=transform.fit_transform(x)
print(x)

  (0, 0)	1.0
  (0, 892)	1.0
  (0, 893)	3.0
  (0, 894)	22.0
  (0, 895)	1.0
  (0, 897)	523.0
  (0, 898)	523.0
  (1, 1)	1.0
  (1, 891)	1.0
  (1, 893)	1.0
  (1, 894)	38.0
  (1, 895)	1.0
  (1, 897)	596.0
  (1, 898)	596.0
  (2, 2)	1.0
  (2, 891)	1.0
  (2, 893)	3.0
  (2, 894)	26.0
  (2, 897)	669.0
  (2, 898)	669.0
  (3, 3)	1.0
  (3, 891)	1.0
  (3, 893)	1.0
  (3, 894)	35.0
  (3, 895)	1.0
  :	:
  (887, 891)	1.0
  (887, 893)	1.0
  (887, 894)	19.0
  (887, 897)	14.0
  (887, 898)	14.0
  (888, 888)	1.0
  (888, 891)	1.0
  (888, 893)	3.0
  (888, 894)	29.69911764705882
  (888, 895)	1.0
  (888, 896)	2.0
  (888, 897)	675.0
  (888, 898)	675.0
  (889, 889)	1.0
  (889, 892)	1.0
  (889, 893)	1.0
  (889, 894)	26.0
  (889, 897)	8.0
  (889, 898)	8.0
  (890, 890)	1.0
  (890, 892)	1.0
  (890, 893)	3.0
  (890, 894)	32.0
  (890, 897)	466.0
  (890, 898)	466.0


In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
from sklearn import svm
lr=svm.SVC()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix:
[[96 14]
 [45 24]]


In [27]:
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)

Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.87      0.76       110
           1       0.63      0.35      0.45        69

    accuracy                           0.67       179
   macro avg       0.66      0.61      0.61       179
weighted avg       0.66      0.67      0.64       179



In [28]:
result2 = accuracy_score(y_test,y_pred)*100.2
print("Accuracy:",result2)

Accuracy: 67.1731843575419
